### ISSUE TITLE
seeds

### ISSUE THREAD

**Issue by DoctorVortex** [Focamacho/MysticalCreations#1]
i what to stop you getting a seed for the crop can you help

**Comment by focamacho** [comment]
Tier 6 seeds don't drop additional seeds by default

**Comment by DoctorVortex** [comment]
ok i'll try that thanks :)

**Comment by DoctorVortex** [comment]
nope they still drop seeds even at T6 even made new ones to test they still drop seed is there a way to stop that in the config?

**Comment by focamacho** [comment]
Do you want something like crops that can only be harvested once?

Tier 6 crops drops only one seed and don't have a chance to drop two seeds.

**Comment by DoctorVortex** [comment]
im making a pack so the only way to get seeds is crafting them there is a config in mystical agriculture to stop seeds dropping of the crop but i can do it with the custom ones 
this is the line
# Percentage chance of a second seed dropping. [range: 0 ~ 100, default: 10]
    I:seed_chance=0

**Comment by focamacho** [comment]
Mystical Creations should respect this number from Mystical Agriculture config
![image](https://user-images.githubusercontent.com/48870573/74115300-5a8ec780-4b8d-11ea-891d-0ac25b959f58.png)

It's dropping a second seed even with seed_chance=0 ?

**Comment by DoctorVortex** [comment]
its dropping 1 seed i want it to be 0 like the others is what im saying in the mod config i get to do that in this mod i cant

**Comment by focamacho** [comment]
Sorry but i still can't understand
When I set the Mystical Agriculture seed chance to 0, it always will drop only one seed.
(Coal Seeds(Mystical Agriculture) and Cake Seeds(Mystical Creations) in the image)
![image](https://user-images.githubusercontent.com/48870573/74115685-1b617600-4b8f-11ea-9085-6a84a630ca7b.png)

This is not right?
Because if you didn't drop any seed from it, it would just disappear and you wouldn't be able to plant it again, would you?

**Comment by DoctorVortex** [comment]
im live on https://www.twitch.tv/d0ctorvortex right now if you got time i can show you what i mean

**Comment by focamacho** [comment]
[mod inside.zip](https://github.com/Focamacho/MysticalCreations/files/4178826/mod.inside.zip)

**Comment by DoctorVortex** [comment]
thats for the fix your awesome

**Comment by madacrex** [comment]
@focamacho I wanna make a prosperity shard seed with Mystical Customization u know more of code than me, u wanna help me?
