### ISSUE TITLE
Can't start on server

### ISSUE THREAD

**Issue by RocksonLee** [Focamacho/MysticalCreations#5]
[crash-2021-01-01_09.15.44-server.txt](https://github.com/Focamacho/MysticalCreations/files/5758531/crash-2021-01-01_09.15.44-server.txt)
| LCHE  | mysticalcreations   | 1.5          | MysticalCreations-1.12.2-1.5.jar

**Comment by focamacho** [comment]
I believe it was fixed in version 1.6. (https://www.curseforge.com/minecraft/mc-mods/mystical-creations/files/3154898)
Thanks for the report!

Happy new year!
